name: Quality Check
on: [push, pull_request]
jobs:
    quality:
        name: Quality Check
        runs-on: ubuntu-latest
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ vars.TURBO_TEAM }}
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
    
          - name: Install node.js v18
            uses: actions/setup-node@v3
            with:
              node-version: 18
    
          - name: Install dependencies
            uses: ./actions/yarnCache

          - name: Build
            run: yarn build
    
          - name: ESLint
            run: yarn lint
